### PR TITLE
Feature - #3858 - GL Selection Action/Reducer

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
This PR is to be checked along with the corresponding PR in translationCore repo

- This PR addresses each project and each tool having its own selected Gateway Language, where the selector on the tool card will save itself to the card's state as well as to the projectDetailsReducer. This allows the tool to have access to its gateway language to show content for that GL, such as tW article headers and content.

#### Please include detailed Test instructions for your pull request:
- [ ] Checkout the corresponding branch name, feature-richmahn-3858, in the translationCore repo, the translationWords repo, and the tC_resources repo (the tC_ressources repo branch was made for testing, not as a PR, just to have Hindi tW content)
- [ ] Delete the ~/translationCore/resources/hi directory if exists
- [ ] Run `npm i` in the root directory of your trancationCore repo. 
- [ ] Run the app and go to a project's tool page. You should be able to pick between English and Hindi in each tool's GL selection. 
- [ ] Select English (already selected) for tW and go into the tool. All should be in English. 
- [ ] Go back to the tool card page and select Hindi for tW, go into the tool, it should now show text in Hindi on the left (tW group indexes), in the blue check card into in the middle (tW group index and the first paragraph of the group article), and in the article on the right.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/112)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[__tests__/Container.test.js, line 26 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112#-L6HaLBJXpji3k6HxdfD:-L6HaLBJXpji3k6HxdfE:bb752ax) ([raw file](https://github.com/translationcoreapps/translationwords/blob/d397a3240b9af8e165ceeed0f1e86d346ae18a11/__tests__/Container.test.js#L26)):*
> ```JavaScript
>     groupsIndex: [{'id': 'groupId1', 'name': 'group title'}, {'id': 'groupId2', 'name': 'group title2'}]
>   },
>   toolsReuder: {
> ```

Typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112)*

**Comment by richmahn** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/Container.test.js, line 26 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112#-L6HaLBJXpji3k6HxdfD:-L6Hf0xFZz1Pff12Z3mB:b-d5q2ho) ([raw file](https://github.com/translationcoreapps/translationwords/blob/d397a3240b9af8e165ceeed0f1e86d346ae18a11/__tests__/Container.test.js#L26)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Fixed. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112#-:-L6HkHneurvf1cmvKbrY:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112#-:-L6Ih3u-XtiX5OuhNbiS:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/112)*

**Pull request merged**
