### PR TITLE
Bugfix #4145/Fix localization gaps

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Finish Localization for tW tool

#### Please include detailed Test instructions for your pull request:
- This PR to be tested with latest develop branch and https://github.com/translationCoreApps/VerseCheck/pull/97
- This PR primarily enables localization in VerseCheck tool.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/118)

### CODE REVIEW

**Comment by mannycolon** [comment]
Core Review: `PENDING CHANGES`
Local test:`PENDING`

**Comment by richmahn** [comment]
Code Review: LGTM other than what Manny recommended
Local test: LGTM

---

Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/components/View.js, line 79 at r2](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/118#-L8nIyD_DT2Jj1qlwiO8:-L8nmQOk63UfjLQOJfDm:b-ucecoy) ([raw file](https://github.com/translationcoreapps/translationwords/blob/e582884c372ca24d3c1572b916a6cc06d3bc9e38/src/components/View.js#L79)):*
>             <Translat

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/118#-:-L8nmdxf04bL89VIwUbT:b-f7xvc8)*

**Comment by PhotoNomad0** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/View.js, line 79 at r2](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/118#-L8nIyD_DT2Jj1qlwiO8:-L8oTsiyARiZQkzkqpgB:b-896fix) ([raw file](https://github.com/translationcoreapps/translationwords/blob/e582884c372ca24d3c1572b916a6cc06d3bc9e38/src/components/View.js#L79)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

>             <Translat
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/118)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/118)*

**Pull request merged**
