### PR TITLE
Default view for the Scripture Pane left: GL ULB - center target language - right: blank

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Default view for the Scripture Pane left: GL ULB - center target language - right: blank

#### Please include detailed Test instructions for your pull request:
- Delete your settings.json folder.
-  Load a project in tW and the scripture pane should have the following bibles loaded:
    - **Left:** GL ULB - **Center:** target language -  **Right:** blank
- Test with both English and Hindi as the GL for the project.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/115)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/115)*

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/115)*

**Comment by klappy** [comment]
Reviewed 1 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/115)*

**Comment by RoyalSix** [comment]
everything `LGTM`

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/115#-:-L7R8G7glF7tZpiphZzW:bnfp4nl)*

**Pull request merged**
