### PR TITLE
Feature mcleanb 3086/show invalidated on verseCheck

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- on verse edit, sets invalidation flag on any selections that are not longer valid in verse.
- on new selection, clears the invalidation flag for that selection
- on tw startup, verify all selections to make sure they are still valid.

#### Testing
- for local testing use current develop branch of tC

On local testing, verseCheck with invalidated should look like example in https://github.com/unfoldingWord-dev/translationCore/issues/3086, except with dark background.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/125)

### CODE REVIEW

**Comment by mannycolon** [comment]
@PhotoNomad0 This steps may be helpful for testing 
https://github.com/translationCoreApps/tc-ui-toolkit/commit/c44913ecff486f6a5935793d7862112bb0dd24fa

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @PhotoNomad0)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/125)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

---

*[package.json, line 70 at r3](https://reviewable.io/reviews/translationcoreapps/translationwords/125#-LEmEQrA9QwA0AYpwn4N:-LEplbLC5XPDA3Ls-Ax5:buvkjds) ([raw file](https://github.com/translationcoreapps/translationwords/blob/40beb34de1ed61e5c63c4c74fa24e17f413b061b/package.json#L70)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

You're using 0.8.0 in the core, is this ok?
</blockquote></details>

Done. Changed for testing branch.

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/125)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 3 files at r5.
Review status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mannycolon and @PhotoNomad0)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/125)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 6 files at r1, 1 of 10 files at r2, 1 of 5 files at r3, 2 of 3 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/125)*

**Pull request merged**
