### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
run ```npm test```
Use component in main app and ensure usual functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/106)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106#-:-L39ZxKCTQD6MYzbsNRA:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106#-L3ULsLk4m6rchy00IoY:-L3ULsLk4m6rchy00IoZ:b-hnp0pv) ([raw file](https://github.com/translationcoreapps/translationwords/blob/b599c8ccc8bf8e8a06952e7dc9ea504866a52e8d/__tests__/AddSomeTests.test.js#L2)):*
> ```JavaScript
> test('We have tests', () => {
>     expect(true).toBeTruthy();
> ```

I thought we wanted this test to fail to indicate we need to add tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106#-L3ULsLk4m6rchy00IoY:-L3UMeTkNYOyTaoJWAnj:brm0qsx) ([raw file](https://github.com/translationcoreapps/translationwords/blob/b599c8ccc8bf8e8a06952e7dc9ea504866a52e8d/__tests__/AddSomeTests.test.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I thought we wanted this test to fail to indicate we need to add tests?
</blockquote></details>

I was not aware of this. I can change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/106#-:-L3Y3aB08z1TNL3XSneO:bnfp4nl)*

**Pull request merged**
