### PR TITLE
Feature - #3303 - tW code cleanup, tests, and linting fixes

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Cleans up tW and adds tests

#### How to test this pull request:

Run tests, run tW in app, look for any problems

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/108)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/USFMParse.js, line 1 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-L4h7rClJmW334KdRXrP:-L4h7rClJmW334KdRXrQ:bjq5t1n) ([raw file](https://github.com/translationcoreapps/translationwords/blob/ba7ffe8c220448c592f82c2474a688cd4b3513d8/src/USFMParse.js#L1)):*
> ```JavaScript
> /* eslint-env jest */
> ```

I hope that we are not still using this file or its functions. Can you verify and then delete it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 9 of 26 files at r1, 6 of 7 files at r3, 1 of 1 files at r4.
Review status: 16 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 9 of 26 files at r1.
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 26 files at r1.
Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by richmahn** [comment]
Review status: 24 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/USFMParse.js, line 1 at r4](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-L4h7rClJmW334KdRXrP:-L4hI3hW4fCn_hrTwNE8:btfkhnt) ([raw file](https://github.com/translationcoreapps/translationwords/blob/ba7ffe8c220448c592f82c2474a688cd4b3513d8/src/USFMParse.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I hope that we are not still using this file or its functions. Can you verify and then delete it?
</blockquote></details>

Deleted, as well as Door43DataFetcher.js

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 2 of 11 files at r5.
Review status: 21 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r5.
Review status: 22 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r5.
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r5.
Review status: 24 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 2 of 11 files at r5.
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-:-L4hMKpHYiJlZ7hm4jPV:bnfp4nl)*

**Comment by klappy** [comment]
I didn't mean to add the LGTM when I'm the first reviewer. It was force of habit.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-:-L4hNBVi0YAbwLpY7Y3y:b-y4lov1)*

**Comment by mannycolon** [comment]
Reviewed 14 of 27 files at r1, 4 of 7 files at r3, 1 of 1 files at r4, 8 of 12 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[package.json, line 47 at r5](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/108#-L4hQA8Q7o7kX_YHhTRz:-L4hQA8Q7o7kX_YHhTS-:b5zmpul) ([raw file](https://github.com/translationcoreapps/translationwords/blob/fd7ce98e27e696a3b28cdf4639e18d6d8d003b0f/package.json#L47)):*
> ```JSON
>     "eslint": "4.15.0",
>     "eslint-plugin-react": "7.5.1",
>     "fs-extra": "5.0.0",
> ```

we may want to use "fs-extra": "4.0.3"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
*[package.json, line 47 at r5](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-L4hQA8Q7o7kX_YHhTRz:-L4hR5KTodgswbANGt9_:b-r1ij03) ([raw file](https://github.com/translationcoreapps/translationwords/blob/fd7ce98e27e696a3b28cdf4639e18d6d8d003b0f/package.json#L47)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we may want to use "fs-extra": "4.0.3"
</blockquote></details>

Good catch!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by richmahn** [comment]
Review status: 24 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 47 at r5](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-L4hQA8Q7o7kX_YHhTRz:-L4hX4F5VycySD33voFN:b-pij3cw) ([raw file](https://github.com/translationcoreapps/translationwords/blob/fd7ce98e27e696a3b28cdf4639e18d6d8d003b0f/package.json#L47)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good catch!!
</blockquote></details>

Ah, I even meant to go back and downgrade that... thanks for catching that. fixing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 2 of 4 files at r6.
Review status: 24 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r6.
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
Reviewed 1 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/108#-:-L4hsyq84lBhjcVhkKQP:bnfp4nl)*

**Pull request merged**
