### PR TITLE
Updates From QA Fail 4318

### PR DESCRIPTION
**Pull request by RoyalSix**
The issues brought up in the comment by koz at the end should be resolved expect for the 10th one 
https://github.com/translationCoreApps/tc-ui-toolkit/pull/35

To test with tc-ui-kit branch
run` npm i translationCoreApps/tc-ui-toolkit#feature-jay-4318`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132)

### CODE REVIEW

**Comment by mannycolon** [comment]
@RoyalSix should I run `npm i translationCoreApps/tc-ui-toolkit#feature-jay-4318` in the core or the tool?

**Comment by RoyalSix** [comment]
@mannycolon on the core should work

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @RoyalSix)

---

*[src/Container.js, line 39 at r1](https://reviewable.io/reviews/translationcoreapps/translationwords/132#-LEukUJK1pc3s217iyDr:-LEukUJK1pc3s217iyDs:b-mgutn4) ([raw file](https://github.com/translationcoreapps/translationwords/blob/d828257934f78f3d19c1cc4cc5afa76e24272a57/src/Container.js#L39)):*
> ```JavaScript
>   componentWillMount() {
>     settingsHelper.loadCorrectPaneSettings(this.props, this.props.tc.actions.setToolSettings);
>     this.toggleHelps();
> ```

Wouldnt just making showHelps true instead of false in the state be better than calling this.toggleHelps() in componentWillMount?

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132)*

**Comment by mannycolon** [comment]
I ran `npm i translationCoreApps/tc-ui-toolkit#feature-jay-4318` in the core but i don't seem to get your changes. For example,  I still see the dark blue color in the progress circles in the menu.

**Comment by RoyalSix** [comment]
@mannycolon can you try again, should be fixed now

---

Review status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132#-:-LEyU9Sx1E_69MTFAPuF:b-cp775l)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132)*

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132#-:-LF-2Dvf8r58xMU-nVJt:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Reviewed 2 of 2 files at r4, 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/132)*

**Pull request merged**
