### PR TITLE
Enhancement - #3305 - CheckCard uses Gateway Language resources index.json

### PR DESCRIPTION
**Pull request by richmahn**
NOTE: Dependent on https://github.com/unfoldingWord-dev/translationCore/pull/3859 also being merged.

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Gets the Group Index from the resources directory based on the Gateway language (currently hard coded as 'en' due to there not being a Gateway Language reducer, to be fixed in #3858) rather than from the project directory, thus no longer copies in the group index.json file. This causes the Check Info card to properly show the title of the selected tW word.

#### Please include detailed Test instructions for your pull request:
- Checkout enhancement-3305-tw-check-info in the main tC repo (https://github.com/unfoldingWord-dev/translationCore/pull/3859) AND in the tC_apps/translationWords repo, load a new project, go into tW. Words should be properly show up as English on the left menu and in the Check Info card. In the `<user>/translationCore/projects/<project>/.apps/translationCore/index/translationWords` directory there should NO LONGER be a index.json file, as we now read it from `<user>/translationCore/resources/en/translationHelps/translationWords/v6/kt`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/110)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Comment by klappy** [comment]
*[src/components/View.js, line 36 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110#-L5UQrlitGcEBp1t0Bcj:-L5UQrlitGcEBp1t0Bck:bpn9jrm) ([raw file](https://github.com/translationcoreapps/translationwords/blob/0e19795c9e4d0736d8eb04732f7dbc2e4d6459a4/src/components/View.js#L36)):*
> ```JavaScript
>     let title;
>     if (this.props.groupsIndexReducer.groupsIndex) {
>       title = this.props.groupsIndexReducer.groupsIndex.filter(item=>item.id===articleId)[0].name;
> ```

The more I think about this. It would be better to do this logic at the container level and pass it in. The view will rerender too often and this will slow the app down.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Comment by RoyalSix** [comment]
*[src/components/View.js, line 36 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110#-L5UQrlitGcEBp1t0Bcj:-L5UZmFfzvOPVM-mNi8I:bn1wz0t) ([raw file](https://github.com/translationcoreapps/translationwords/blob/0e19795c9e4d0736d8eb04732f7dbc2e4d6459a4/src/components/View.js#L36)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The more I think about this. It would be better to do this logic at the container level and pass it in. The view will rerender too often and this will slow the app down.
</blockquote></details>

:thumbsup:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Comment by richmahn** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/View.js, line 36 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110#-L5UQrlitGcEBp1t0Bcj:-L5UoUDnx1WLrf6GgXeO:bb6un1j) ([raw file](https://github.com/translationcoreapps/translationwords/blob/0e19795c9e4d0736d8eb04732f7dbc2e4d6459a4/src/components/View.js#L36)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/110)*

**Pull request merged**
