### PR TITLE
translationWords Rewrite (with tc-ui-toolkit)

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR removes the logic from all the components in tW and uses the tc-ui-toolkit module to render components.

#### Please include detailed Test instructions for your pull request:
- Pull the branch feature-jay-4318 on translationCore branch
- Ensure all functionality is the same as before
  - Every piece of code in tW was touched so this needs to be thoroughly checked
- Ensure all component are visually the same as before.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[package.json, line 67 at r1](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LCeOqSVEqtzKU4GnSzQ:-LCeOqSVEqtzKU4GnSzR:b-gffbrw) ([raw file](https://github.com/translationcoreapps/translationwords/blob/658ea4eec6bd92d61d3b74cbc39cbe6c75552be9/package.json#L67)):*
> ```JSON
>     "react-remarkable": "1.1.1",
>     "tc-tool": "1.3.0",
>     "tc-ui-toolkit": "github:translationCoreApps/tc-ui-toolkit#feature-jay-4313",
> ```

Nice job doing this hack to get going with the tW refactor

---

*[src/Container.js, line 55 at r1](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LCePG6cDs0bMv0iNsgz:-LCePG6cDs0bMv0iNsh-:b-l7evut) ([raw file](https://github.com/translationcoreapps/translationwords/blob/658ea4eec6bd92d61d3b74cbc39cbe6c75552be9/src/Container.js#L55)):*
> ```JavaScript
>       ["other", "Other"]
>     ];
> ```

It looks like we need to find a way to move out a lot of the business logic that i currently in this file. What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Container.js, line 55 at r1](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LCePG6cDs0bMv0iNsgz:-LCeSNFY0MsAa1Af7OwR:b2mg0tt) ([raw file](https://github.com/translationcoreapps/translationwords/blob/658ea4eec6bd92d61d3b74cbc39cbe6c75552be9/src/Container.js#L55)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

It looks like we need to find a way to move out a lot of the business logic that i currently in this file. What do you think?
</blockquote></details>

Yes. There is definitely a lot but I was thinking it might be easier after Joels API is in the core. But this is a container so logic should be expected here if it has to do with preparing data for the UI.
We might want to create more helpers to organize it all.

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/Container.js, line 55 at r1](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LCePG6cDs0bMv0iNsgz:-LCeTiiW31m-pSeRSsvC:b-x575u2) ([raw file](https://github.com/translationcoreapps/translationwords/blob/658ea4eec6bd92d61d3b74cbc39cbe6c75552be9/src/Container.js#L55)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Yes. There is definitely a lot but I was thinking it might be easier after Joels API is in the core. But this is a container so logic should be expected here if it has to do with preparing data for the UI.
We might want to create more helpers to organize it all.
</blockquote></details>

Yes, it is true we can expect to have some business logic in the container but not this much. If possible we may want, like you said, move a good part of the business logic to helper functions outside of the container.js

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Reviewed 12 of 13 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 67 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj0yiW9Y14Ts7TR0hQ:-LDj0yiX9AIyJku-WIAM:b-985ear) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/package.json#L67)):*
> ```JSON
>     "react-remarkable": "1.1.1",
>     "tc-tool": "^1.5.0",
>     "tc-ui-toolkit": "github:translationCoreApps/tc-ui-toolkit#feature-jay-scripture-pane-fix",
> ```

do we want to use the actual latest version of `tc-ui-toolkit`?

---

*[src/containers/CheckInfoCardContainer.js, line 3 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1P-D2a_bKt3joGbN:-LDj1P-D2a_bKt3joGbO:bn179gm) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/CheckInfoCardContainer.js#L3)):*
> ```JavaScript
> import React from 'react';
> import {CheckInfoCard} from 'tc-ui-toolkit';
> ```

nice job moving business logic to containers

---

*[src/containers/GroupMenuContainer.js, line 32 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1bRO209de3YePI3Q:-LDj1bRP7GMo4lshLGEa:b-7aqgma) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/GroupMenuContainer.js#L32)):*
> ```JavaScript
>     return (
>       <GroupMenu
>         translate={translate}
> ```

I thought we said we would move the locale to the tools? or is that part of another story?

---

*[src/containers/ScripturePaneContainer.js, line 28 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1kP36dQT0SMZu329:-LDj1kP36dQT0SMZu32A:b-xhg4i0) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/ScripturePaneContainer.js#L28)):*
> ```JavaScript
>       currentPaneSettings
>     } = this.props;
>     const titleLabel = "Step 1. Read";
> ```

We are going to need to implement locale here

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/containers/ScripturePaneContainer.js, line 28 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1kP36dQT0SMZu329:-LDj2aGi3TE8HuK--sSc:bqpu2h0) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/ScripturePaneContainer.js#L28)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

We are going to need to implement locale here
</blockquote></details>

isn't that part of the story ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 67 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj0yiW9Y14Ts7TR0hQ:-LDrYwmI-W9aa9Wna3_Q:b32vmt) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/package.json#L67)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we want to use the actual latest version of `tc-ui-toolkit`?
</blockquote></details>

??

---

*[src/containers/GroupMenuContainer.js, line 32 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1bRO209de3YePI3Q:-LDrZ3Zz8SAznM0W-lco:b32vmt) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/GroupMenuContainer.js#L32)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I thought we said we would move the locale to the tools? or is that part of another story?
</blockquote></details>

??

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by RoyalSix** [comment]
Review status: 24 of 27 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/containers/GroupMenuContainer.js, line 32 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1bRO209de3YePI3Q:-LEA_YIp1iPyLB4L-FT4:b-twxyg8) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/GroupMenuContainer.js#L32)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

??
</blockquote></details>

The locale right now is in the tool (translationWords) where should it be?

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by RoyalSix** [comment]
Review status: 24 of 27 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/containers/ScripturePaneContainer.js, line 28 at r4](https://reviewable.io/reviews/translationcoreapps/translationwords/123#-LDj1kP36dQT0SMZu329:-LEA_mQHBqXU1w5bn8Il:b-z7c7g8) ([raw file](https://github.com/translationcoreapps/translationwords/blob/6153f74e8f94d8a2a2ed3cbe47881fbe3ae896c6/src/containers/ScripturePaneContainer.js#L28)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

isn't that part of the story ?
</blockquote></details>

I will move it

---


*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Comment by mannycolon** [comment]
Hey when I opened tW and this is what it looks like. (It's missing the top bar)

screen shot 2018-06-06 at 11 48 19 am

**Comment by mannycolon** [comment]
This doenst look right
screen shot 2018-06-06 at 11 48 19 am

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/123)*

**Pull request merged**
