### PR TITLE
Adds Localization Support

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):

This related to https://github.com/unfoldingWord-dev/translationCore/issues/3891
This utilizes a new [tool HOC](https://github.com/translationCoreApps/tc-tool) that adds locale support to tc apps.

#### Please include detailed Test instructions for your pull request:

I could only find one word to localize "See more". I added a localization for German you can try out.
Also, make sure I didn't break the tool!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/111)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/111#-:-L6IpaGj0KerSqtEtjwt:bnfp4nl)*

**Comment by neutrinog** [comment]
There's a bug in tC core that needs to be fixed before this can be merged.

**Comment by neutrinog** [comment]
This is now ready to go. As a short term fix we installed the required dependencies in tC. see https://github.com/unfoldingWord-dev/translationCore/pull/3902

**Comment by neutrinog** [comment]
Blocked by https://github.com/unfoldingWord-dev/translationCore/pull/3902

**Comment by RoyalSix** [comment]
Reviewed 9 of 14 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/translationwords/111)*

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing Review: `Pending...`

**Comment by RoyalSix** [comment]
It appears that translation Helps is not loading on this PR @neutrinog

**Comment by RoyalSix** [comment]
If I open the tool in a language, and then go back and change the local I get the following error
screen shot 2018-03-05 at 2 06 16 pm

**Comment by neutrinog** [comment]
@RoyalSix fixed.

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 9 of 14 files at r1, 5 of 6 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/111#-:-L6san2FQX3dmbgSwH_X:bnfp4nl)*

**Comment by richmahn** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationwords/111)*

**Pull request merged**
