### PR TITLE
Integrates new GroupedMenu into tW

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingword-dev/translationcore/issues/5710 and  https://github.com/unfoldingWord-dev/translationCore/issues/4443
- Integrates the new GroupedMenu into tW.

#### Please include detailed Test instructions for your pull request:
- Be sure to test this PR along with ~https://github.com/translationcoreapps/tc-ui-toolkit/issues/164~ https://github.com/unfoldingWord-dev/translationCore/pull/5715 otherwise nothing will work!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationwords/226)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Code Review: `LGTM`
Local Testing: `Pending...`

**Comment by RoyalSix** [comment]
@neutrinog 
image

I think we might need a little less left padding on the group menu headers (accuse, accuses, accused).  Not sure if that is a small enough difference to get passed through QA

**Comment by RoyalSix** [comment]
Also, the diameter of the progress circle looks a few pixels bigger than before

**Comment by neutrinog** [comment]
I spoke with Koz and he said the icons and and padding were not a big deal.

**Comment by neutrinog** [comment]
I'm fixing the tests I forgot to update.

**Pull request merged**
